table _tempAverage
	lineageTag: f8f69800-bb07-4f97-9477-e70bfc611772

	measure _tempSum =
			
			AVERAGE( _tempAverage[Value] )
		formatString: 0
		lineageTag: fa71848a-8c63-472d-9e5c-bc70915db738

	column YEAR
		dataType: string
		lineageTag: c84c1b87-bb60-4fdc-99f9-5d55f15e407e
		summarizeBy: none
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: a22a5cc4-2bbd-418e-a401-779c732d36a8
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 8e27ffae-b50d-4827-acf9-8bd699300adf
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _tempAverage = m
		mode: import
		queryGroup: powerbi_imported_datasets
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fVlZjttKDLyLvzNG78tZgtz/Gk/uKpLVcfCAgTWjkZpbsbj49+9X3r2/fr3qOz2f", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [YEAR = _t, JAN = _t, FEB = _t, MAR = _t, APR = _t, MAY = _t, JUN = _t, JUL = _t, AUG = _t, SEP = _t, OCT = _t, NOV = _t, DEC = _t, AVERAGE = _t, WINTER = _t, SPRING = _t, SUMMER = _t, AUTUMN = _t, #"(blank)" = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"WINTER", "SPRING", "SUMMER", "AUTUMN", "(blank)"}),
				    unpivot = Table.UnpivotOtherColumns(#"Removed Columns", {"YEAR"}, "Attribute", "Value"),
				    all = unpivot,
				    #"Filtered Rows" = Table.SelectRows(all, each ([Attribute] <> "AVERAGE")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Value", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

