table revenue
	lineageTag: 6075cdc1-1381-4f8e-925a-ffc8432bbca4

	/// SUM of Column: 'rawData'[Sales Revenue]
	measure Sales = SUM('revenue'[Sales Revenue])
		formatString: "£"#,0
		displayFolder: __Measures
		lineageTag: f9954a1a-4fe0-49a7-92e2-dcbf1b176bea

	/// SUM of Column: 'rawData'[Sold Items]
	measure Sold = SUM('revenue'[Sold Items])
		formatString: #,0
		displayFolder: __Measures
		lineageTag: b0ff220d-e750-4387-a0f0-83a456de9ff6

	/// SUM of Column: 'rawData'[Unit Cost]
	measure Total_Revenue = SUM('revenue'[Unit Cost])
		formatString: "£"#,0;-"£"#,0;"£"#,0
		displayFolder: __Measures
		lineageTag: 5810c52a-f9bc-4979-8586-6fff982c3c34

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure Orders =
			
			COUNTROWS( 'revenue' )
		formatString: 0
		displayFolder: __Measures
		lineageTag: 66ed84f4-2d16-4bd8-ad9d-4e94a233f8e9

	measure Unit_Cost =
			
			MAX( 'revenue'[Unit Cost] )
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		displayFolder: __Measures
		lineageTag: d000361f-ca76-4f09-8291-9fe13c6fd0c7

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column Product
		dataType: string
		lineageTag: 4d6bc1f3-3348-4549-a3af-6b7464241609
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Sales Revenue'
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 08afa748-1010-4615-a409-0c15c67be283
		summarizeBy: sum
		sourceColumn: Sales Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Unit Cost'
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: d1778bfa-3811-44f7-80af-1bb22e676fee
		summarizeBy: sum
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Sold Items'
		dataType: int64
		formatString: 0
		lineageTag: 7fb38df8-e654-4296-a66a-410eaafb81cc
		summarizeBy: sum
		sourceColumn: Sold Items

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: d7b142ee-edfb-499a-b456-b0cb24d9eaed
		summarizeBy: count
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	partition revenue = m
		mode: import
		queryGroup: powerbi_imported_datasets
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZVRLrtwwDLtKMOvA0P9zi+4fBm/R7gsU7f0rWw6QQTZObGdIkaLm6+v148/vX/9+/v3G1/k68oSw+YJQa0LUCiPVksTS1w7XCsD11BiZyQrEfRqGxHTtOAhMeCLSYFUjgaR593qfN+pJdvAp1C/z+9QFwQYYqd6AmDduG+gUnAq22UjQwah3XhW7+YTBUTfJDCwP7vn1QafpotYlChYCeUIKNTjFjZkLL8Iocp+SIobE5YEnha+Sse5Kd9X/VM3L51OamXTZ2TKVHDFV2gL/oHYLC8hLJrKLgG8LrCzPzSwJjGmCD+aJe/gZbbdNUsT2O6rcRLamFrtR+xAnDjHT7bDce52p6ZS9K2rjBHz6rYvyBImVt0lg/RtjS7OgRle9UUvBs5qXz306DfUNP8p75iRs89xAaVr+oF7BjlNgyY65ImzZMcOC0rut/opZEFWqezCm7PIeQnciIYBCur2j6kAsfHtwe1veM3SsUCp3mgPB2NG7zTvpzY0AV5jnDFztmNLBll4ezFQZA5kV4AdnO3zKGqVjNdh4we5W3x3GgVzxEdojth9li1fiOlFJnCncOf+gyqXq9Oj2zjUawWrgK6/cpefHn8fwoHTNHXvQGqGZqV2Bs6viDhQJqUO36/V+/wc=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Product = _t, #"Sales Revenue" = _t, #"Unit Cost" = _t, #"Sold Items" = _t, h_Profict = _t, x_c = _t, y_c = _t, n_Squares = _t, Area_column = _t, w_Square = _t, Colonna1 = _t, #"make evident" = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"h_Profict", "x_c", "y_c", "n_Squares", "Area_column", "w_Square", "Colonna1", "make evident"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Unit Cost", Currency.Type}, {"Sales Revenue", Currency.Type}, {"Sold Items", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "OrderID", each {1..[Sold Items]}  ),
				    #"Expanded Orders" = Table.ExpandListColumn(#"Added Custom", "OrderID"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded Orders",{{"OrderID", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

