table ___measures
	lineageTag: 951d63f2-f64a-4063-acda-9d21e80d8f25

	measure '# orders' =
			
			DISTINCTCOUNT( fct_sales[Order Number] )
		formatString: 0
		lineageTag: f1e76c0e-3180-408f-893b-3b6426db0997

	measure '£ sales' =
			
			SUM( fct_sales[Net Price] )
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: fc7117c5-a930-4bde-82e2-01ab9ed60658

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '£ sales 2024' =
			
			CALCULATE(
			    [£ sales],
			    KEEPFILTERS(dim_dates[YearNUM] == 2024)
			)
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: e9c6a99a-b51e-45cd-97d6-e9f6024396b9

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '£ sales 2023' =
			
			CALCULATE(
			    [£ sales],
			    KEEPFILTERS(dim_dates[YearNUM] == 2023)
			)
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: 6a5fdc24-d54f-491e-b28b-0cd0c8708a33

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '£ sales 2022' =
			
			CALCULATE(
			    [£ sales],
			    KEEPFILTERS(dim_dates[YearNUM] == 2022)
			)
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: 42c46347-8f34-45ca-902b-312575802bc2

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column Column1
		dataType: string
		isHidden
		lineageTag: add38eaa-ab32-4980-96de-c7e03d3037b9
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition ___measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t])
				in
				    Source

	annotation PBI_ResultType = Table

